deploy:
  stage: deploy
  image: docker
  services:
    - docker:dind
  only:
    refs:
      - production
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE/production .
    - docker push $CI_REGISTRY_IMAGE/production